default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: rails
  password: rails

development:
  <<: *default
  database: bowling_development

test:
  <<: *default
  database: bowling_test

production:
  <<: *default
  database: bowling_production
